# Creates and publishes a new release build based on the created release tag.
name: YoMap Release

on:
  push:
    tags:
      - release-*
  workflow_dispatch:

env:
  flutter_version: "3.13.0"
  java_version: "11.x"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Decode google-services.json file
        env:
          ENCODED_STRING: ${{ secrets.GOBLOB_GSERVICES_PARAM }}
        run: echo $ENCODED_STRING | base64 --decode > android/app/google-services.json
      - name: Decode android.keystore file
        env:
          ENCODED_STRING: ${{ secrets.GOBLOB_ANDROID_KEYSTORE }}
        run: echo $ENCODED_STRING | base64 --decode > android/app/android.keystore
      - name: Decode Service Account file
        env:
          ENCODED_STRING: ${{ secrets.G_SERVICE_ACCOUNT }}
        run: echo $ENCODED_STRING | base64 --decode > android/app/service_account.json
      - name: Build AAB
        run: |
          TAG_VERSION=$(git describe --abbrev=0 --tags)
          TAG_COMMENT=$(git tag -l --format='%(contents)' $TAG_VERSION)
          echo $TAG_COMMENT > changelog/whatsnew/whatsnew-en-US
          BUILD_NAME=$(echo $TAG_VERSION | grep -Eo '[0-9]+.[0-9]+.[0-9]+')
          TAG_NUMBERS=$(echo $BUILD_NAME | tr "." "\n")
          VERSION_NUMBER_LIST=$(for c in ${TAG_NUMBERS[@]}; do if [ $(echo -n "$c" | wc -c) -eq 1 ]; then echo "0$c"; else echo $c; fi; done)
          VERSION_NUMBER=""
          for c in ${VERSION_NUMBER_LIST[@]}; do VERSION_NUMBER="$VERSION_NUMBER$c"; done
          BUILD_NUMBER=$(echo "22$VERSION_NUMBER")
          echo "Building version $BUILD_NAME ($BUILD_NUMBER)"
          flutter build appbundle --build-name=${BUILD_NAME} --build-number=${BUILD_NUMBER}
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Create Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: build/app/outputs/bundle/release/app-release.aab
          GHR_REPLACE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: android/app/service_account.json
          packageName: me.yomap
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: beta
          status: completed
          inAppUpdatePriority: 5
          whatsNewDirectory: changelog/whatsnew
